services:
#    soap.example:
#        class: SoapBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  soap_service:
    class: 'SoapBundle\Service\SoapService'
    # apply some configuration to these services
    autowire: false
    public: true
    tags: ['soap_service']
    arguments: ['@doctrine.orm.entity_manager']