mi06\VitrineBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nom:
            type: string
            length: 100
        email:
            type: string
            length: 100
        password:
            type: string
            length: 100
            
    oneToMany:
        commande:
            targetEntity: Commande
            mappedBy: client