soap:
    resource: "@SoapBundle/Resources/config/routing.yml"
    prefix:   /

mi06_vitrine:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: mi06_vitrine_homepage
        permanent: true

mi06_vitrine_local:
    resource: "@mi06VitrineBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: fr|en

mi06_soap:
    resource: "@SoapBundle/Resources/config/routing.yml"
    prefix:   /api/
    requirements:
        _locale: fr|en

app:
    resource: '@AppBundle/Controller/'
    type: annotation
