# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        mi06\VitrineBundle\Entity\Client:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        utilisateurs:
            entity:
                class: mi06VitrineBundle:Client
                property: email
    
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout
                target: /
    
    access_control:
        - { path: ^/backoffice, roles: ROLE_ADMIN }
        - { path: ^/client, roles: ROLE_USER }
