# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        mi06\VitrineBundle\Entity\Client:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        utilisateurs:
            entity:
                class: mi06VitrineBundle:Client
                property: email
    
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: mi06_client_login
                check_path: mi06_client_login
            logout:
                path: mi06_client_logout
                target: mi06_vitrine_homepage
    
    access_control:
        - { path: "^/[a-z]{2}/backoffice", roles: ROLE_ADMIN }
        - { path: "^/[a-z]{2}/profil", roles: ROLE_USER }
        - { path: "^/[a-z]{2}/validationPanier", roles: ROLE_USER }
