articlecategorie_index:
    path:     /
    defaults: { _controller: "mi06VitrineBundle:ArticleCategorie:index" }
    methods:  GET

articlecategorie_show:
    path:     /{id}/show
    defaults: { _controller: "mi06VitrineBundle:ArticleCategorie:show" }
    methods:  GET

articlecategorie_new:
    path:     /new
    defaults: { _controller: "mi06VitrineBundle:ArticleCategorie:new" }
    methods:  [GET, POST]

articlecategorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "mi06VitrineBundle:ArticleCategorie:edit" }
    methods:  [GET, POST]

articlecategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "mi06VitrineBundle:ArticleCategorie:delete" }
    methods:  DELETE
