mi06_vitrine_home_backoffice:
    path:     /
    defaults: { _controller: mi06VitrineBundle:ArticleCategorie:index }
    
mi06_vitrine_articlecategorie:
    resource: "@mi06VitrineBundle/Resources/config/routing/articlecategorie.yml"
    prefix:   /articlecategorie

mi06_vitrine_commande:
    resource: "@mi06VitrineBundle/Resources/config/routing/commande.yml"
    prefix:   /commande
    
mi06_vitrine_article:
    resource: "@mi06VitrineBundle/Resources/config/routing/article.yml"
    prefix:   /article