commande_index:
    path:     /
    defaults: { _controller: "mi06VitrineBundle:Commande:index" }
    methods:  GET

commande_show:
    path:     /{id}/show
    defaults: { _controller: "mi06VitrineBundle:Commande:show" }
    methods:  GET

commande_edit:
    path:     /{id}/edit
    defaults: { _controller: "mi06VitrineBundle:Commande:edit" }
    methods:  [GET, POST]
