mi06_vitrine_homepage:
    path:     /
    defaults: { _controller: mi06VitrineBundle:Default:index, name: Visiteur }

mi06_vitrine_local:
    path:     /local/{newLocal}
    defaults: { _controller: mi06VitrineBundle:Default:setLocal}

mi06_vitrine_client:
    resource: "@mi06VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /profil

mi06_vitrine_commande:
    resource: "@mi06VitrineBundle/Resources/config/routing/commande.yml"
    prefix:   /commande

mi06_vitrine_backoffice:
    resource: "@mi06VitrineBundle/Resources/config/routing/backoffice.yml"
    prefix:   /backoffice

mi06_vitrine_catalogue:
    path:     /catalogue/
    defaults: { _controller: mi06VitrineBundle:Default:catalogue }
    
mi06_articles_caterorie:
    path:     /articlesParCategorie/{id}
    defaults: { _controller: mi06VitrineBundle:Default:articlesParCategorie }
    
mi06_vitrine_mentions:
    path:     /mentions/
    defaults: { _controller: mi06VitrineBundle:Default:mentions }
    
mi06_panier:
    path:     /panier/
    defaults: { _controller: mi06VitrineBundle:Panier:contenuPanier }
    
mi06_ajout_article:
    path:     /ajoutArticle/{idArticle}/quantite/{quantite}
    defaults: { _controller: mi06VitrineBundle:Panier:ajoutArticle, quantite: 1}
    
mi06_vider_panier:
    path:     /viderPanier/
    defaults: { _controller: mi06VitrineBundle:Panier:viderPanier}

mi06_validation_panier:
    path:     /validationPanier/
    defaults: { _controller: mi06VitrineBundle:Panier:validationPanier}

mi06_validation_panier:
    path:     /validationPanier/
    defaults: { _controller: mi06VitrineBundle:Panier:validationPanier}

mi06_client_login:
    path:     /login
    defaults: { _controller: "mi06VitrineBundle:Client:login" }
    methods:  [GET, POST]

mi06_client_create:
    path:     /create
    defaults: { _controller: "mi06VitrineBundle:Client:create" }
    methods:  [GET, POST]

mi06_client_logout:
    path:     /logout
