services:
#    mi06_vitrine.example:
#        class: mi06\VitrineBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  montant_panier:
    class: 'mi06\VitrineBundle\Service\MontantPanier'
    # apply some configuration to these services
    autowire: false
    public: true
    tags: ['montant_panier']
    arguments: ['@doctrine.orm.entity_manager']