services:
#    mi06_vitrine.example:
#        class: mi06\VitrineBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  panier_service:
    class: 'mi06\VitrineBundle\Service\PanierService'
    # apply some configuration to these services
    autowire: false
    public: true
    tags: ['panier_service']
    arguments: ['@doctrine.orm.entity_manager']